[devshell]
packages = [
  "alejandra",
  "dprint",
  "nixops-plugged",
  "dhall",
  "dhall-json",
  "dhall-lsp-server",
  "nodejs-18_x",
  "nodePackages.pnpm",
]

[[commands]]
package = "treefmt"
category = "formatter"
