name: Deploy

on:
  push:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary
          name: id_ed25519
          config: |
            Host *
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
            Host webserver
              HostName ${{secrets.WEBSERVER_HOST}} 
              User root
              Port ${{ secrets.WEBSERVER_PORT }}
              IdentityFile ~/.ssh/id_ed25519
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
          name: sno2wman
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix-shell --run "cat ./nixops/secrets.dhall | dhall-to-json > ./nixops/secrets.json"
        env:
          WEBSERVER_HOST: ${{secrets.WEBSERVER_HOST}}
          WEBSERVER_PORT: ${{secrets.WEBSERVER_PORT}}
      - run: nix-shell --run "nixops deploy"
