name: Deploy

on:
  push:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
          name: sno2wman
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{secrets.WEBSERVER_HOST}} ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ02RYFEONAr/5a3fokBYHUFVPqF8G64DxhV5RGu7gtK
          name: id_ed25519
      - run: nix-shell --run "cat ./nixops/secrets.dhall | dhall-to-json > ./nixops/secrets.json"
        env:
          WEBSERVER_HOST: ${{secrets.WEBSERVER_HOST}} 
          WEBSERVER_PORT: ${{secrets.WEBSERVER_PORT}} 
      - run: nix-shell --run "nixops deploy"