name: Deploy

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            nixops:
              - 'nixops/**'

  nixops:
    name: NixOps
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.nixops == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary
          name: id_ed25519
          config: |
            Host *
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
            Host webserver
              HostName ${{secrets.WEBSERVER_HOST}} 
              User root
              Port ${{ secrets.WEBSERVER_PORT }}
              IdentityFile ~/.ssh/id_ed25519
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: sno2wman
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix-shell --run "cat ./nixops/secrets.dhall | dhall-to-json > ./nixops/secrets.json"
        env:
          WEBSERVER_HOST: ${{secrets.WEBSERVER_HOST}}
          WEBSERVER_PORT: ${{secrets.WEBSERVER_PORT}}
      - run: nix-shell --run "nixops deploy"
